// Expanded Mythological Entities Database - 100+ entities
const expandedEntitiesDatabase = [
    // Greek & Roman Mythology (25 entities)
    { name: "Zeus", culture: "Greek", blurb: "King of the gods, ruler of Mount Olympus and the sky.", domainKeywords: ['sky'], personality: "powerful, commanding, promiscuous, arrogant", power: "controls lightning and thunder, king of gods", domain: "sky god, ruler of Olympus" },
    { name: "Hades", culture: "Greek", blurb: "God of the underworld and the dead.", domainKeywords: ['underworld', 'death'], personality: "stern, wealthy, possessive, solitary", power: "rules the underworld, commands the dead", domain: "god of the underworld, death, and riches" },
    { name: "Poseidon", culture: "Greek", blurb: "God of the sea, earthquakes, and storms.", domainKeywords: ['sea', 'land'], personality: "moody, tempestuous, powerful, creative", power: "controls seas, earthquakes, creates horses", domain: "god of the sea, earthquakes, and storms" },
    { name: "Apollo", culture: "Greek", blurb: "God of music, arts, knowledge, and light.", domainKeywords: ['sun', 'wisdom', 'art'], personality: "artistic, healing, prophetic, rational", power: "controls music, archery, prophecy, light", domain: "god of music, arts, knowledge, and light" },
    { name: "Athena", culture: "Greek", blurb: "Goddess of wisdom, courage, and strategic warfare.", domainKeywords: ['wisdom', 'war'], personality: "wise, strategic, courageous, disciplined", power: "excels in warfare and wisdom, crafts", domain: "goddess of wisdom, courage, and strategic warfare" },
    { name: "Hermes", culture: "Greek", blurb: "Messenger of the gods; god of trade, thieves, and travelers.", domainKeywords: ['trickster', 'land'], personality: "quick, witty, charming, agile, boundary-crosser", power: "superhuman speed, messenger of the gods", domain: "god of trade, travelers, and thieves" },
    { name: "Aphrodite", culture: "Greek", blurb: "Goddess of love, beauty, and desire.", domainKeywords: ['love', 'beauty'], personality: "beautiful, seductive, passionate, vain", power: "inspires love and desire, controls beauty", domain: "goddess of love, beauty, and desire" },
    { name: "Ares", culture: "Greek", blurb: "God of war, courage, and bloodshed.", domainKeywords: ['war', 'chaos'], personality: "violent, aggressive, fearless, bloodthirsty", power: "incites war, grants courage in battle", domain: "god of war, courage, and bloodshed" },
    { name: "Artemis", culture: "Greek", blurb: "Goddess of the hunt, wilderness, and the moon.", domainKeywords: ['hunting', 'moon', 'forest'], personality: "independent, fierce, protective, wild", power: "master archer, protects women and children", domain: "goddess of the hunt, wilderness, and moon" },
    { name: "Dionysus", culture: "Greek", blurb: "God of wine, fertility, and ecstasy.", domainKeywords: ['fertility', 'chaos', 'transformation'], personality: "wild, ecstatic, transformative, liberating", power: "controls wine and madness, brings ecstasy", domain: "god of wine, fertility, and ecstasy" },
    { name: "Hephaestus", culture: "Greek", blurb: "God of fire, metalworking, and craftsmanship.", domainKeywords: ['fire', 'crafts'], personality: "skilled, patient, creative, deformed", power: "master craftsman, controls fire", domain: "god of fire, metalworking, and craftsmanship" },
    { name: "Demeter", culture: "Greek", blurb: "Goddess of agriculture, harvest, and fertility.", domainKeywords: ['fertility', 'land'], personality: "nurturing, protective, grieving, powerful", power: "controls crops and seasons", domain: "goddess of agriculture, harvest, and fertility" },
    { name: "Hestia", culture: "Greek", blurb: "Goddess of the hearth, home, and family.", domainKeywords: ['home', 'order'], personality: "peaceful, domestic, protective, modest", power: "protects homes and families", domain: "goddess of the hearth, home, and family" },
    { name: "Persephone", culture: "Greek", blurb: "Queen of the underworld, goddess of spring.", domainKeywords: ['underworld', 'fertility'], personality: "dual-natured, transformative, powerful", power: "rules underworld, brings spring", domain: "queen of the underworld, goddess of spring" },
    { name: "Eros", culture: "Greek", blurb: "God of love and sexual desire.", domainKeywords: ['love'], personality: "playful, mischievous, passionate", power: "inspires love and desire", domain: "god of love and sexual desire" },
    { name: "Pan", culture: "Greek", blurb: "God of the wild, shepherds, and rustic music.", domainKeywords: ['forest', 'wild'], personality: "wild, musical, lustful, playful", power: "controls nature, creates panic", domain: "god of the wild, shepherds, and rustic music" },
    { name: "Cupid", culture: "Roman", blurb: "God of love and desire.", domainKeywords: ['love'], personality: "playful, mischievous, romantic", power: "inspires love with arrows", domain: "god of love and desire" },
    { name: "Janus", culture: "Roman", blurb: "God of beginnings, gates, and transitions.", domainKeywords: ['order', 'transformation'], personality: "dual-faced, wise, transitional", power: "sees past and future", domain: "god of beginnings and transitions" },
    { name: "Vesta", culture: "Roman", blurb: "Goddess of the hearth and home.", domainKeywords: ['home', 'order'], personality: "protective, domestic, sacred", power: "protects the sacred flame", domain: "goddess of the hearth and home" },
    { name: "Minerva", culture: "Roman", blurb: "Goddess of wisdom, arts, and warfare.", domainKeywords: ['wisdom', 'art', 'war'], personality: "wise, strategic, creative", power: "excels in wisdom and crafts", domain: "goddess of wisdom, arts, and warfare" },
    { name: "Neptune", culture: "Roman", blurb: "God of the sea and earthquakes.", domainKeywords: ['sea', 'land'], personality: "powerful, moody, creative", power: "controls seas and earthquakes", domain: "god of the sea and earthquakes" },
    { name: "Pluto", culture: "Roman", blurb: "God of the underworld and wealth.", domainKeywords: ['underworld', 'wealth'], personality: "stern, wealthy, powerful", power: "rules the underworld", domain: "god of the underworld and wealth" },
    { name: "Mercury", culture: "Roman", blurb: "Messenger god of trade and travel.", domainKeywords: ['trickster', 'land'], personality: "quick, clever, boundary-crossing", power: "superhuman speed, messenger", domain: "messenger god of trade and travel" },
    { name: "Venus", culture: "Roman", blurb: "Goddess of love, beauty, and fertility.", domainKeywords: ['love', 'beauty', 'fertility'], personality: "beautiful, seductive, life-giving", power: "inspires love and beauty", domain: "goddess of love, beauty, and fertility" },
    { name: "Mars", culture: "Roman", blurb: "God of war and agriculture.", domainKeywords: ['war', 'land'], personality: "warlike, protective, fertile", power: "brings victory in war", domain: "god of war and agriculture" },

    // Norse Mythology (15 entities)
    { name: "Odin", culture: "Norse", blurb: "The All-Father; god of wisdom, war, and death.", domainKeywords: ['wisdom', 'war', 'death', 'sky'], personality: "wise, relentless, sacrificial, mysterious", power: "seeks knowledge, commands ravens, god of war", domain: "all-father, god of wisdom, war, and death" },
    { name: "Thor", culture: "Norse", blurb: "God of thunder, lightning, and strength, protector of mankind.", domainKeywords: ['sky', 'war'], personality: "strong, protective, brave, hot-tempered", power: "wields Mjolnir, controls thunder, immense strength", domain: "god of thunder, lightning, and strength" },
    { name: "Loki", culture: "Norse", blurb: "Trickster god of mischief, known for his cunning and shapeshifting.", domainKeywords: ['trickster', 'fire'], personality: "cunning, mischievous, chaotic, shapeshifter", power: "creates illusions, changes form, causes chaos", domain: "trickster god of mischief" },
    { name: "Freya", culture: "Norse", blurb: "Goddess of love, beauty, fertility, and war.", domainKeywords: ['love', 'war'], personality: "beautiful, loving, fierce, independent", power: "rules over love, fertility, and war", domain: "goddess of love, beauty, and war" },
    { name: "Frigg", culture: "Norse", blurb: "Goddess of marriage, motherhood, and domestic life.", domainKeywords: ['love', 'home'], personality: "maternal, protective, wise, domestic", power: "protects families, sees the future", domain: "goddess of marriage, motherhood, and domestic life" },
    { name: "Tyr", culture: "Norse", blurb: "God of war, law, and justice.", domainKeywords: ['war', 'justice'], personality: "brave, just, honorable, sacrificial", power: "god of war and justice", domain: "god of war, law, and justice" },
    { name: "Baldr", culture: "Norse", blurb: "God of light, purity, and beauty.", domainKeywords: ['sun', 'beauty'], personality: "pure, beautiful, beloved, tragic", power: "embodies light and purity", domain: "god of light, purity, and beauty" },
    { name: "Heimdall", culture: "Norse", blurb: "Guardian of the Bifrost bridge, god of vigilance.", domainKeywords: ['sky', 'order'], personality: "vigilant, protective, wise, alert", power: "guards Asgard, sees and hears all", domain: "guardian of the Bifrost bridge" },
    { name: "Njord", culture: "Norse", blurb: "God of the sea, wind, and wealth.", domainKeywords: ['sea', 'wind'], personality: "peaceful, wealthy, generous, wise", power: "controls seas and winds", domain: "god of the sea, wind, and wealth" },
    { name: "Skadi", culture: "Norse", blurb: "Goddess of winter, hunting, and mountains.", domainKeywords: ['hunting', 'mountain'], personality: "independent, fierce, wild, vengeful", power: "controls winter and hunting", domain: "goddess of winter, hunting, and mountains" },
    { name: "Frey", culture: "Norse", blurb: "God of fertility, prosperity, and peace.", domainKeywords: ['fertility', 'land'], personality: "peaceful, prosperous, generous, fertile", power: "brings prosperity and fertility", domain: "god of fertility, prosperity, and peace" },
    { name: "Hel", culture: "Norse", blurb: "Goddess of the dead and ruler of Helheim.", domainKeywords: ['death', 'underworld'], personality: "stern, impartial, powerful, cold", power: "rules over the dead in Helheim", domain: "goddess of the dead and ruler of Helheim" },
    { name: "Fenrir", culture: "Norse", blurb: "Giant wolf, son of Loki, destined to kill Odin.", domainKeywords: ['chaos', 'destruction'], personality: "ferocious, bound, destructive, powerful", power: "will devour Odin at Ragnarok", domain: "giant wolf of destruction" },
    { name: "Jormungandr", culture: "Norse", blurb: "World serpent, son of Loki, encircles Midgard.", domainKeywords: ['sea', 'chaos'], personality: "massive, destructive, ancient, powerful", power: "encircles the world, causes earthquakes", domain: "world serpent of chaos" },
    { name: "Sleipnir", culture: "Norse", blurb: "Eight-legged horse of Odin.", domainKeywords: ['sky', 'speed'], personality: "swift, loyal, magical, noble", power: "travels between worlds", domain: "eight-legged magical horse" },

    // Egyptian Mythology (15 entities)
    { name: "Ra", culture: "Egyptian", blurb: "The sun god, one of the most important gods in ancient Egypt.", domainKeywords: ['sun', 'sky', 'creator'], personality: "majestic, life-giving, powerful, creator", power: "sails across the sky, brings the sun, creates life", domain: "sun god, creator deity" },
    { name: "Anubis", culture: "Egyptian", blurb: "God of death, mummification, and the afterlife.", domainKeywords: ['death', 'underworld'], personality: "solemn, just, protective, guide", power: "weighs hearts, guides souls, protects tombs", domain: "god of death, embalming, and the afterlife" },
    { name: "Isis", culture: "Egyptian", blurb: "Goddess of magic, motherhood, and healing; wife of Osiris.", domainKeywords: ['magic', 'love', 'creator'], personality: "magical, maternal, healing, devoted", power: "uses powerful magic, resurrects the dead", domain: "goddess of magic, motherhood, and healing" },
    { name: "Osiris", culture: "Egyptian", blurb: "God of the underworld, resurrection, and fertility.", domainKeywords: ['underworld', 'death', 'land'], personality: "just, regenerative, civilizing, deceased", power: "rules the underworld, grants life from death", domain: "god of the underworld, resurrection, and fertility" },
    { name: "Horus", culture: "Egyptian", blurb: "God of the sky, war, and protection.", domainKeywords: ['sky', 'war'], personality: "protective, vengeful, royal, divine", power: "protects pharaohs, god of war", domain: "god of the sky, war, and protection" },
    { name: "Thoth", culture: "Egyptian", blurb: "God of wisdom, writing, and the moon.", domainKeywords: ['wisdom', 'moon'], personality: "wise, scholarly, just, creative", power: "invented writing, judges the dead", domain: "god of wisdom, writing, and the moon" },
    { name: "Sekhmet", culture: "Egyptian", blurb: "Goddess of war, healing, and the sun.", domainKeywords: ['war', 'sun'], personality: "fierce, protective, healing, destructive", power: "brings plagues and healing", domain: "goddess of war, healing, and the sun" },
    { name: "Bastet", culture: "Egyptian", blurb: "Goddess of home, fertility, and cats.", domainKeywords: ['home', 'fertility'], personality: "protective, nurturing, fierce, graceful", power: "protects homes and families", domain: "goddess of home, fertility, and cats" },
    { name: "Set", culture: "Egyptian", blurb: "God of chaos, storms, and the desert.", domainKeywords: ['chaos', 'storm'], personality: "chaotic, destructive, powerful, jealous", power: "controls storms and chaos", domain: "god of chaos, storms, and the desert" },
    { name: "Ma'at", culture: "Egyptian", blurb: "Goddess of truth, justice, and cosmic order.", domainKeywords: ['justice', 'order'], personality: "just, balanced, truthful, cosmic", power: "maintains cosmic order", domain: "goddess of truth, justice, and cosmic order" },
    { name: "Ptah", culture: "Egyptian", blurb: "Creator god, patron of craftsmen and architects.", domainKeywords: ['creator', 'crafts'], personality: "creative, skilled, divine, artistic", power: "creates through thought and word", domain: "creator god, patron of craftsmen" },
    { name: "Hathor", culture: "Egyptian", blurb: "Goddess of love, beauty, music, and motherhood.", domainKeywords: ['love', 'beauty', 'art'], personality: "beautiful, loving, musical, maternal", power: "inspires love, music, and joy", domain: "goddess of love, beauty, music, and motherhood" },
    { name: "Sobek", culture: "Egyptian", blurb: "Crocodile god of the Nile and military might.", domainKeywords: ['water', 'war'], personality: "powerful, protective, fierce, territorial", power: "protects the Nile, grants military strength", domain: "crocodile god of the Nile and military might" },
    { name: "Khnum", culture: "Egyptian", blurb: "Ram-headed god who creates humans on his potter's wheel.", domainKeywords: ['creator', 'crafts'], personality: "creative, skilled, divine, artistic", power: "creates humans from clay", domain: "creator god who shapes humans" },
    { name: "Nut", culture: "Egyptian", blurb: "Sky goddess who arches over the earth.", domainKeywords: ['sky', 'cosmos'], personality: "maternal, protective, cosmic, eternal", power: "protects the earth, mother of stars", domain: "sky goddess who arches over earth" },

    // Japanese Mythology (10 entities)
    { name: "Amaterasu", culture: "Japanese", blurb: "Sun goddess, ruler of the heavens.", domainKeywords: ['sun', 'sky'], personality: "radiant, benevolent, noble", power: "shines light upon the world", domain: "sun goddess" },
    { name: "Susanoo", culture: "Japanese", blurb: "God of storms and the sea.", domainKeywords: ['sea', 'sky'], personality: "violent, heroic, wild", power: "controls storms", domain: "god of storms and sea" },
    { name: "Kitsune", culture: "Japanese", blurb: "Magical fox spirits.", domainKeywords: ['trickster', 'magic'], personality: "intelligent, cunning, loyal", power: "shapeshifting, illusions", domain: "yokai fox spirit" },
    { name: "Ryujin", culture: "Japanese", blurb: "Dragon god of the sea.", domainKeywords: ['sea', 'dragon'], personality: "powerful, majestic, dangerous", power: "controls tides", domain: "dragon god of the sea" },
    { name: "Tsukuyomi", culture: "Japanese", blurb: "God of the moon and night.", domainKeywords: ['moon'], personality: "mysterious, nocturnal, divine", power: "controls the moon", domain: "god of the moon and night" },
    { name: "Inari", culture: "Japanese", blurb: "God of rice, agriculture, and foxes.", domainKeywords: ['fertility', 'land'], personality: "benevolent, prosperous, protective", power: "brings prosperity and fertility", domain: "god of rice, agriculture, and foxes" },
    { name: "Benzaiten", culture: "Japanese", blurb: "Goddess of music, art, and water.", domainKeywords: ['art', 'water'], personality: "artistic, flowing, beautiful", power: "inspires art and music", domain: "goddess of music, art, and water" },
    { name: "Bishamonten", culture: "Japanese", blurb: "God of war and warriors.", domainKeywords: ['war'], personality: "martial, protective, righteous", power: "protects warriors and brings victory", domain: "god of war and warriors" },
    { name: "Daikokuten", culture: "Japanese", blurb: "God of wealth, commerce, and agriculture.", domainKeywords: ['wealth', 'fertility'], personality: "prosperous, generous, protective", power: "brings wealth and prosperity", domain: "god of wealth, commerce, and agriculture" },
    { name: "Fukurokuju", culture: "Japanese", blurb: "God of wisdom, longevity, and happiness.", domainKeywords: ['wisdom', 'longevity'], personality: "wise, ancient, benevolent", power: "grants wisdom and long life", domain: "god of wisdom, longevity, and happiness" },

    // Hindu Mythology (10 entities)
    { name: "Shiva", culture: "Hindu", blurb: "The destroyer and transformer.", domainKeywords: ['destruction', 'creation'], personality: "ascetic, destructive, powerful", power: "destroys the universe to recreate it", domain: "the destroyer" },
    { name: "Vishnu", culture: "Hindu", blurb: "The preserver and protector.", domainKeywords: ['creator', 'land'], personality: "benevolent, protective, righteous", power: "maintains cosmic order", domain: "the preserver" },
    { name: "Ganesha", culture: "Hindu", blurb: "Remover of obstacles.", domainKeywords: ['wisdom', 'land'], personality: "wise, benevolent, patron", power: "removes obstacles", domain: "god of beginnings" },
    { name: "Kali", culture: "Hindu", blurb: "Goddess of time and change.", domainKeywords: ['destruction', 'death'], personality: "fierce, liberating, untamed", power: "destroys evil forces", domain: "goddess of time and destruction" },
    { name: "Lakshmi", culture: "Hindu", blurb: "Goddess of wealth, fortune, and prosperity.", domainKeywords: ['fertility', 'wealth'], personality: "benevolent, prosperous, beautiful", power: "brings wealth and prosperity", domain: "goddess of wealth, fortune, and prosperity" },
    { name: "Saraswati", culture: "Hindu", blurb: "Goddess of knowledge, music, and arts.", domainKeywords: ['wisdom', 'art'], personality: "wise, artistic, pure", power: "grants knowledge and creativity", domain: "goddess of knowledge, music, and arts" },
    { name: "Durga", culture: "Hindu", blurb: "Goddess of war and protection.", domainKeywords: ['war'], personality: "fierce, protective, powerful", power: "protects against evil", domain: "goddess of war and protection" },
    { name: "Hanuman", culture: "Hindu", blurb: "Monkey god of strength and devotion.", domainKeywords: ['war'], personality: "devoted, strong, loyal", power: "possesses immense strength", domain: "monkey god of strength and devotion" },
    { name: "Krishna", culture: "Hindu", blurb: "God of love, compassion, and protection.", domainKeywords: ['love', 'wisdom'], personality: "loving, wise, playful, protective", power: "protects devotees, brings joy", domain: "god of love, compassion, and protection" },
    { name: "Rama", culture: "Hindu", blurb: "God of righteousness and virtue.", domainKeywords: ['justice', 'war'], personality: "righteous, virtuous, protective", power: "embodies perfect dharma", domain: "god of righteousness and virtue" },

    // Chinese Mythology (8 entities)
    { name: "Sun Wukong", culture: "Chinese", blurb: "The Monkey King trickster hero.", domainKeywords: ['trickster', 'war'], personality: "rebellious, powerful, clever", power: "supernatural strength, 72 transformations", domain: "monkey king" },
    { name: "Jade Emperor", culture: "Chinese", blurb: "Supreme deity of heaven.", domainKeywords: ['sky', 'order'], personality: "supreme, just, powerful", power: "rules over all gods", domain: "supreme deity of heaven" },
    { name: "Guanyin", culture: "Chinese", blurb: "Goddess of mercy and compassion.", domainKeywords: ['love'], personality: "compassionate, merciful, healing", power: "grants mercy and healing", domain: "goddess of mercy and compassion" },
    { name: "Dragon King", culture: "Chinese", blurb: "Ruler of the seas and weather.", domainKeywords: ['sea', 'dragon'], personality: "powerful, majestic, controlling", power: "controls weather and seas", domain: "ruler of the seas and weather" },
    { name: "Chang'e", culture: "Chinese", blurb: "Goddess of the moon.", domainKeywords: ['moon'], personality: "beautiful, lonely, eternal", power: "lives on the moon", domain: "goddess of the moon" },
    { name: "Nuwa", culture: "Chinese", blurb: "Creator goddess who created humans.", domainKeywords: ['creator', 'fertility'], personality: "creative, maternal, protective", power: "created humans from clay", domain: "creator goddess who created humans" },
    { name: "Fuxi", culture: "Chinese", blurb: "God of civilization and culture.", domainKeywords: ['wisdom', 'creator'], personality: "wise, civilizing, creative", power: "taught humans civilization", domain: "god of civilization and culture" },
    { name: "Lei Gong", culture: "Chinese", blurb: "God of thunder and lightning.", domainKeywords: ['sky', 'storm'], personality: "powerful, just, thunderous", power: "controls thunder and lightning", domain: "god of thunder and lightning" },

    // Aztec/Mesoamerican Mythology (5 entities)
    { name: "Quetzalcoatl", culture: "Aztec", blurb: "Feathered serpent creator god.", domainKeywords: ['creator', 'sky', 'wisdom'], personality: "wise, creative, benevolent", power: "creator of mankind", domain: "god of wind and wisdom" },
    { name: "Huitzilopochtli", culture: "Aztec", blurb: "God of war and the sun.", domainKeywords: ['war', 'sun'], personality: "warlike, powerful, demanding", power: "requires human sacrifice", domain: "god of war and the sun" },
    { name: "Tlaloc", culture: "Aztec", blurb: "God of rain and fertility.", domainKeywords: ['fertility', 'water'], personality: "life-giving, powerful, moody", power: "controls rain and storms", domain: "god of rain and fertility" },
    { name: "Tezcatlipoca", culture: "Aztec", blurb: "God of the night sky and sorcery.", domainKeywords: ['sky', 'magic'], personality: "mysterious, powerful, trickster", power: "controls fate and sorcery", domain: "god of the night sky and sorcery" },
    { name: "Xochiquetzal", culture: "Aztec", blurb: "Goddess of love, beauty, and fertility.", domainKeywords: ['love', 'beauty', 'fertility'], personality: "beautiful, loving, life-giving", power: "inspires love and fertility", domain: "goddess of love, beauty, and fertility" },

    // African Mythology (5 entities)
    { name: "Anansi", culture: "Akan", blurb: "Trickster god of stories.", domainKeywords: ['trickster', 'wisdom'], personality: "clever, tricky, storyteller", power: "obtains all stories", domain: "trickster god of stories" },
    { name: "Ogun", culture: "Yoruba", blurb: "God of iron, war, and technology.", domainKeywords: ['war', 'crafts'], personality: "powerful, protective, skilled", power: "controls iron and warfare", domain: "god of iron, war, and technology" },
    { name: "Yemaya", culture: "Yoruba", blurb: "Goddess of the ocean and motherhood.", domainKeywords: ['sea', 'love'], personality: "maternal, powerful, nurturing", power: "protects mothers and children", domain: "goddess of the ocean and motherhood" },
    { name: "Shango", culture: "Yoruba", blurb: "God of thunder, lightning, and justice.", domainKeywords: ['sky', 'justice'], personality: "powerful, just, passionate", power: "controls thunder and lightning", domain: "god of thunder, lightning, and justice" },
    { name: "Orunmila", culture: "Yoruba", blurb: "God of wisdom and divination.", domainKeywords: ['wisdom', 'magic'], personality: "wise, prophetic, mysterious", power: "sees the future, grants wisdom", domain: "god of wisdom and divination" },

    // Celtic Mythology (5 entities)
    { name: "The Morrigan", culture: "Celtic", blurb: "Goddess of war, fate, and death.", domainKeywords: ['war', 'death', 'magic'], personality: "prophetic, fierce, protective", power: "foretells doom, incites battle", domain: "goddess of war and fate" },
    { name: "Cernunnos", culture: "Celtic", blurb: "Horned god of the forest and animals.", domainKeywords: ['forest', 'fertility'], personality: "wild, primal, protective", power: "protects forests and animals", domain: "horned god of the forest and animals" },
    { name: "Brigid", culture: "Celtic", blurb: "Goddess of fire, poetry, and healing.", domainKeywords: ['fire', 'art'], personality: "creative, healing, protective", power: "inspires poetry and healing", domain: "goddess of fire, poetry, and healing" },
    { name: "Lugh", culture: "Celtic", blurb: "God of light, crafts, and skills.", domainKeywords: ['sun', 'crafts'], personality: "skilled, bright, talented", power: "master of all crafts", domain: "god of light, crafts, and skills" },
    { name: "Dagda", culture: "Celtic", blurb: "The Good God, father of the gods.", domainKeywords: ['creator', 'fertility'], personality: "powerful, generous, protective", power: "controls life and death", domain: "the good god, father of the gods" },

    // Native American Mythology (5 entities)
    { name: "Coyote", culture: "Native American", blurb: "Trickster god and creator.", domainKeywords: ['trickster', 'creator'], personality: "clever, mischievous, creative", power: "shapes the world through tricks", domain: "trickster god and creator" },
    { name: "Raven", culture: "Native American", blurb: "Trickster god who brought light to the world.", domainKeywords: ['trickster', 'sun'], personality: "clever, transformative, creative", power: "brought light to the world", domain: "trickster god who brought light" },
    { name: "Thunderbird", culture: "Native American", blurb: "Powerful bird spirit of storms.", domainKeywords: ['sky', 'storm'], personality: "powerful, majestic, protective", power: "controls storms and weather", domain: "powerful bird spirit of storms" },
    { name: "White Buffalo Woman", culture: "Native American", blurb: "Sacred woman who brought the pipe to the Lakota.", domainKeywords: ['wisdom', 'sacred'], personality: "sacred, wise, transformative", power: "brought sacred knowledge", domain: "sacred woman who brought wisdom" },
    { name: "Spider Grandmother", culture: "Native American", blurb: "Creator goddess who wove the world.", domainKeywords: ['creator', 'crafts'], personality: "creative, wise, maternal", power: "wove the world into existence", domain: "creator goddess who wove the world" },

    // Mythical Creatures (7 entities)
    { name: "Phoenix", culture: "Mythical", blurb: "A mythical bird of rebirth from ashes.", domainKeywords: ['fire', 'sun', 'creation'], personality: "cyclical, regenerative, gentle", power: "is reborn from ashes", domain: "mythical bird of rebirth" },
    { name: "Dragon", culture: "Mythical", blurb: "Legendary serpentine creature.", domainKeywords: ['dragon', 'fire', 'land'], personality: "powerful, wise, hoarders", power: "breathes fire, flies", domain: "legendary creature" },
    { name: "Unicorn", culture: "Mythical", blurb: "Pure white horse with a single horn.", domainKeywords: ['purity', 'magic'], personality: "pure, gentle, magical", power: "heals with its horn", domain: "mythical creature of purity" },
    { name: "Griffin", culture: "Mythical", blurb: "Eagle-headed lion creature.", domainKeywords: ['sky', 'land'], personality: "noble, protective, fierce", power: "guards treasures", domain: "mythical guardian creature" },
    { name: "Sphinx", culture: "Mythical", blurb: "Lion with human head, guardian of riddles.", domainKeywords: ['wisdom', 'mystery'], personality: "wise, mysterious, protective", power: "poses riddles, guards secrets", domain: "guardian of riddles and wisdom" },
    { name: "Pegasus", culture: "Mythical", blurb: "Winged horse of Greek mythology.", domainKeywords: ['sky', 'freedom'], personality: "noble, free, swift", power: "flies through the sky", domain: "winged horse of freedom" },
    { name: "Centaur", culture: "Mythical", blurb: "Half-human, half-horse creature.", domainKeywords: ['wild', 'wisdom'], personality: "wild, wise, dual-natured", power: "bridges human and animal nature", domain: "half-human, half-horse creature" }
];

// Expose to window for access from ES module scripts
try { window.expandedEntitiesDatabase = expandedEntitiesDatabase; } catch (_) {}